server:
    port: 9007
    servlet:
        context-path: /Service
spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
queueName: city
exchange: jsa.direct
routingkey: jsa.routingkey