server:
    port: 9009
    servlet:
        context-path: /WeatherResponse
spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
queueName: city
exchange: jsa.direct
routingkey: jsa.routingkey